sudo: required
services:
    - docker

before_install:
    - docker build -t lombaardj/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true lombaardj/react-test npm test -- --coverage

after_success:
    - docker build -t lombaardj/multi-client ./client
    - docker build -t lombaardj/multi-nginx ./nginx
    - docker build -t lombaardj/multi-server ./server
    - docker build -t lombaardj/multi-worker ./worker
    #Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to Docker Hub
    - docker push lombaardj/multi-client
    - docker push lombaardj/multi-nginx
    - docker push lombaardj/multi-server
    - docker push lombaardj/multi-worker

deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-447103599473
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY


